### ISSUE TITLE
Familiarize with Draw.io 

### ISSUE THREAD

**Issue by louieb117** [iesus-s/GamesStatsWebsite#9]
- Familiarize yourself with the draw.io tool. If you haven't used it before, explore its features, tutorials, and available templates.
- Create a new draw.io document for your website project.
- Set up an appropriate canvas size and layout for your design. Consider the responsive nature of websites and choose a suitable aspect ratio.

**Comment by ZorgonOmega** [comment]
Uploaded it to the main file
